### ISSUE TITLE
Home page working but Products not coming..

### ISSUE THREAD

**Issue by pratikchourdia** [xaneem/flipkart-api-php#4]
Hi, First of all thanks for this tool.. But from last few days we are unable to get the products using this api. Please check..

**Comment by xaneem** [comment]
Just had a look - the products are not retrieved because Flipkart is not returning the product list. Maybe their API is under maintenance. The code will work fine once their API comes back online.

Here's the JSON returned by the API right now. Note that `productInfoList` is empty.
````
{
    "nextUrl": "https://affiliate-api.flipkart.net/affiliate/feeds/<affiliate-id>/category/v1:reh/v1:reh-cca-h76:WCWDPA7NSPKAU4NY.json?expiresAt=1423678336638&sig=87167677af555afb37d1b0110c7786c2",
    "validTill": 1423678336646,
    "productInfoList": [],
    "lastProductId": ""
}

````
